name = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
email = ""
homepage = "https://youronly.one"
avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"
#emoji = "&#x1FAF0;&#x1F3FE;"
emoji = "❄️"
descriptionshort = "Born a writer and programmer."
descriptionlong = "Lives in the Philippines and have been writing and programming at a young age."
motto = "If this is not the end of oblivion, then I shall live everyday as if my life were to end on this very day."
locationorigin = "Philippines"
locationcurrent = "Philippines"
organization = "Yelosan Publishing"

rel = "me noopener"
#rel = "noopener external nofollow"

### BGN: Wishlist ###
  [[author.gift]]
    name = "Amazon"
    code = ""
    url = "https://www.amazon.com/hz/wishlist/ls/1YHYZNMDYDDB6/ref=nav_wishlist_lists_1?_encoding=UTF8&type=wishlist"
    linktitle = "Wishlist"
    tag = ""
    message = "I love to read. A review is guaranteed for the book you will send as a gift."
    type = "wishlist"
  [[author.gift]]
    name = "Steam"
    code = ""
    url = "https://store.steampowered.com/wishlist/profiles/76561197997196684/#sort=order&discount_any=1"
    linktitle = "Wishlist"
    tag = ""
    message = ""
    type = "wishlist"
### END: Wishlist ###

### BGN: Affiliate codes ###
  [[author.gift]]
    name = "Amazon"
    code = "youronlyone-20"
    url = "https://www.amazon.com?&_encoding=UTF8&tag=youronlyone-20&linkCode=ur2&linkId=387918b08ede21983ce5efc57f10361f&camp=1789&creative=9325"
    linktitle = "youronlyone-20"
    tag = ""
    message = ""
    type = "affiliate"
### END: Affiliate codes ###

### BGN: Tip Jar ###
  #[[author.gift]]
  #  name = "Coins.ph"
  #  code = ""
  #  url = ""
  #  linktitle = ""
  #  tag = ""
  #  message = ""
  #  type = "tip jar"
  [[author.gift]]
    name = "Flattr"
    code = ""
    url = "https://flattr.com/@YourOnlyOne"
    linktitle = "@YourOnlyOne"
    tag = ""
    message = ""
    type = "tip jar"
  #[[author.gift]]
  #  name = "GCash"
  #  code = ""
  #  url = ""
  #  linktitle = ""
  #  tag = ""
  #  message = ""
  #  type = "tip jar"
  [[author.gift]]
    name = "PayPal"
    code = ""
    url = "https://paypal.me/yukino"
    linktitle = ""
    tag = ""
    message = ""
    type = "tip jar"
### END: Tip Jar ###

### BGN: Cryptocurrency ###
  [[author.gift]]
    name = "XLM (Stellar)"
    code = "yukino*keybase.io"
    url = ""
    linktitle = ""
    tag = "gift for https://youronly.one"
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "USDC (Stellar)"
    code = "yukino*keybase.io"
    url = ""
    linktitle = ""
    tag = "gift for https://youronly.one"
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "XRP (XRPL)"
    code = "rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA"
    url = ""
    linktitle = ""
    tag = "246013"
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "ETH (ERC-20)"
    code = "0x739d2aae2a5b7a4e1d64c58d121c9d908d706c83"
    url = ""
    linktitle = ""
    tag = ""
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "USDC (ERC-20)"
    code = "0x739d2aae2a5b7a4e1d64c58d121c9d908d706c83"
    url = ""
    linktitle = ""
    tag = ""
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "XBT (Bitcoin)"
    code = "32w1De4wvr5jEzC4g5P4rkjvqg2bvMR8Vk"
    url = ""
    linktitle = ""
    tag = ""
    message = ""
    type = "cryptocurrency"
  [[author.gift]]
    name = "BCH (BCHN)"
    code = "pp8fkmchlu6a7c53a2s682jd70mncrzemsthca6ftl"
    url = ""
    linktitle = ""
    tag = ""
    message = ""
    type = "cryptocurrency"
### END: Cryptocurrency ###
