name = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
email = ""
homepage = "https://youronly.one"
rel = "me noopener"
#rel = "noopener external nofollow"
avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"
