####### Base Config #######
  baseURL = "https://im.youronly.one"
  title = "I'M YourOnly.One"
  copyright = ""                                          # we are using our own footer
  timeZone = "Asia/Manila"


####### Site settings #######
  #footnoteAnchorPrefix = ""                              # prefix for footnote anchors
  footnoteReturnLinkContents = "↩"                        # text to display for footnote return links
  paginate = 1000
  #paginatePath = "page"                                  # https://example.com/page/2
  rssLimit = 100
  summaryLength = 70

  #### Other settings ####
    #disqusShortname = ""
    #googleAnalytics = ""                     # .Site.GoogleAnalytics


####### Backend settings #######
  canonifyURLs = true                                     # true for our use-case
  #disableAliases = true                                  # use this if we want to use server redirects
  enableEmoji = true                                      # format :smile:
  enableGitInfo = false                                   # it is in Git time
  enableInlineShortcodes = false                          # disabled for security reasons as per Hugo documentation
  enableRobotsTXT = false                                 # Hugo robots.txt template
  relativeURLs = false                                    # false for our use-case; make all relative URLs relative to content root
  refLinksNotFoundURL = "https://im.youronly.one"

  ## Dev settings ##
    publishDir = "../../live/public"
    enableMissingTranslationPlaceholders = true

  ## Other settings ##
    PygmentsCodeFences = true
    PygmentsStyle = "monokai"
    disableKinds = ["taxonomy", "term", "taxonomyTerm", "RSS"]

#### LANG stuff ####
  defaultContentLanguage = "en-ph"
  #defaultContentLanguage = "tl-tglg"
  defaultContentLanguageInSubdir = false                  # false -- homepage is using HTML redirect which is blocked by some browsers
  hasCJKLanguage = true
  languageCode = "en-ph"

  ## Theme settings ##
    pluralizeListTitles = false
  ## Theme settings ##

#######  #######  #######  #######  #######  #######  #######  #######
