workspace = "off"

[[imports]]
  disable = false                           # default: false
  ignoreConfig = false                      # default: false
  ignoreImports = false                     # default: false
  noMounts = false                          # default: false
  noVendor = false                          # default: false
  path = "codeberg.org/yelosan/hugo-feeds"

[[imports]]
  path = "codeberg.org/yelosan/hugo-syndication"

[[imports]]
  path = "codeberg.org/yelosan/hugo-shortcodes"

[[imports]]
  path = "codeberg.org/yelosan/hugo-semantic-web"

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "gitlab.com/youronlyone/images"
  # BGN: /frontpage/ images
    [[imports.mounts]]
      source = "frontpage"
      target = "assets/images"
  # END: /frontpage/ images

[[imports]]
  ignoreConfig = true
  ignoreImports = true
  path = "codeberg.org/youronlyone/content"
  # BGN: /frontpage/ content
    [[imports.mounts]]
      source = "content/frontpage"
      target = "content"
      #lang = "en"
  # END: /frontpage/ content

[[imports]]
  path = "codeberg.org/yelosan/hugo-globals"

[[imports]]
  path = "codeberg.org/youronlyone/defaults"

[[imports]]
  ignoreConfig = true
  path = "github.com/techmagus/hugo-theme-showcase"


# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  [[mounts]]
    source = "content"
    target = "content"

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  [[mounts]]
    source = "static"
    target = "static"
