# <domain>/posts/my-post/atom.xml
page = ["HTML"]                                             # default: HTML

# <domain>/atom.xml
home = ["HTML"]                      # default: HTML, RSS

# <domain>/posts/atom.xml
section = ["HTML"]                           # default: HTML, RSS

# <domain>/tags/atom.xml, <domain>/categories/atom.xml
taxonomy = ["HTML"]                          # default: HTML, RSS

# <domain>/tags/mytag/atom.xml, <domain>/categories/mycat/atom.xml
term = ["HTML"]                              # default: HTML, RSS
